import os
import sys
import hmac

# Explicitly add this file's directory to sys.path so that 'routes' and
# 'services' packages are importable regardless of the working directory
# Python was launched from. Without this, importlib can fail to resolve
# sibling packages in the embedded / packaged environment.
_BACKEND_DIR = os.path.dirname(os.path.abspath(__file__))
if _BACKEND_DIR not in sys.path:
    sys.path.insert(0, _BACKEND_DIR)

from flask import Flask, jsonify, send_from_directory, send_file, request

app = Flask(__name__)

# Reject request bodies larger than 1 MB. Prevents a malicious or runaway
# caller from flooding /claude/messages or /proxy with unbounded payloads.
app.config['MAX_CONTENT_LENGTH'] = 1 * 1024 * 1024  # 1 MB


@app.errorhandler(413)
def request_entity_too_large(e):
    return jsonify({"error": "Request body too large. Maximum size is 1 MB."}), 413


# ── Local-token authentication ────────────────────────────────────────────────
# PSG_LOCAL_TOKEN is a per-session UUID generated by main.js and passed to the
# Flask subprocess via environment variable.  The Electron preload delivers it
# to the renderer via contextBridge so every API fetch can include it in the
# X-PSG-Local-Token request header.  This prevents other processes on the same
# machine from hitting the Flask API without possessing the session token.

_PSG_LOCAL_TOKEN = os.environ.get("PSG_LOCAL_TOKEN", "")

# Routes that must be reachable without a token (health check, static assets).
_TOKEN_EXEMPT_PREFIXES = ("/health",)


@app.before_request
def enforce_local_token():
    """Reject API requests that do not carry the correct session token."""
    # Only enforce when Electron actually injected a token (production mode).
    if not _PSG_LOCAL_TOKEN:
        return  # Dev mode or token not configured — skip enforcement.

    path = request.path

    # Exempt health check and OPTIONS pre-flight requests.
    if request.method == "OPTIONS":
        return
    if any(path.startswith(p) for p in _TOKEN_EXEMPT_PREFIXES):
        return

    # Static frontend assets don't need a token.
    # API routes live under /claude/ and /proxy — enforce on those.
    if not (path.startswith("/claude") or path.startswith("/proxy") or path.startswith("/glassdoor")):
        return

    provided = request.headers.get("X-PSG-Local-Token", "")
    # Use hmac.compare_digest to prevent timing-based token oracle attacks.
    if not provided or not hmac.compare_digest(provided, _PSG_LOCAL_TOKEN):
        return jsonify({"error": "Unauthorized"}), 401

# Directory containing the built frontend. Flask serves these files so
# Electron loads http://127.0.0.1:5001 (same-origin) instead of file://.
_FRONTEND_DIR = os.environ.get("PSG_FRONTEND_DIR", "")


# ── Health check ─────────────────────────────────────────────────────────────
@app.route("/health", methods=["GET"])
def health():
    return jsonify({"status": "ok", "service": "PSG Executive Intelligence"})


# ── API blueprints ────────────────────────────────────────────────────────────
# Registered at module level (standard Flask pattern) so routes exist before
# the first request arrives. Each blueprint is wrapped independently so one
# failure never prevents the others from loading.
try:
    from routes.claude import claude_bp
    app.register_blueprint(claude_bp)
    print("[PSG] Registered: routes.claude")
except Exception as e:
    import traceback
    print(f"[PSG] FAILED routes.claude: {e}")
    traceback.print_exc()

try:
    from routes.proxy import proxy_bp
    app.register_blueprint(proxy_bp)
    print("[PSG] Registered: routes.proxy")
except Exception as e:
    print(f"[PSG] FAILED routes.proxy: {e}")

try:
    from routes.glassdoor import glassdoor_bp
    app.register_blueprint(glassdoor_bp)
    print("[PSG] Registered: routes.glassdoor")
except Exception as e:
    print(f"[PSG] FAILED routes.glassdoor: {e}")


# ── Frontend catch-all (must come after all API blueprints) ──────────────────
@app.route("/", defaults={"path": ""})
@app.route("/<path:path>")
def serve_frontend(path):
    if not _FRONTEND_DIR:
        return jsonify({"error": "Frontend directory not configured"}), 503
    if path:
        candidate = os.path.join(_FRONTEND_DIR, path)
        if os.path.isfile(candidate):
            return send_from_directory(_FRONTEND_DIR, path)
    index = os.path.join(_FRONTEND_DIR, "index.html")
    if os.path.isfile(index):
        return send_file(index)
    return jsonify({"error": "index.html not found"}), 503


if __name__ == "__main__":
    print("[PSG] Backend starting on http://127.0.0.1:5001")
    app.run(host="127.0.0.1", port=5001, debug=False, use_reloader=False)
